project_id = "wrogevjpvhvputrjhvvg"

[functions.apply-fine]
verify_jwt = true

[functions.apply-payment]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false

[functions.generate-export]
verify_jwt = true

[functions.daily-reminders]
verify_jwt = false

[functions.record-authority-payment]
verify_jwt = false