project_id = "wrogevjpvhvputrjhvvg"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.emergency-password-reset]
verify_jwt = false

[functions.admin-update-role]
verify_jwt = true

[functions.admin-deactivate-user]
verify_jwt = true

[functions.apply-fine]
verify_jwt = true

[functions.apply-payment]
verify_jwt = false

[functions.dashboard-kpis]
verify_jwt = false

[functions.emergency-bootstrap]
verify_jwt = false

[functions.generate-insurance-reminders]
verify_jwt = false

[functions.generate-export]
verify_jwt = true

[functions.daily-reminders]
verify_jwt = false

[functions.record-authority-payment]
verify_jwt = false

[functions.reminders-generate]
verify_jwt = false

[functions.reminders-digest]
verify_jwt = false

[functions.settings]
verify_jwt = false