project_id = "wrogevjpvhvputrjhvvg"

[functions.apply-fine]
verify_jwt = true

[functions.apply-payment]
verify_jwt = false

[functions.dashboard-kpis]
verify_jwt = false

[functions.generate-insurance-reminders]
verify_jwt = false

[functions.generate-export]
verify_jwt = true

[functions.daily-reminders]
verify_jwt = false

[functions.record-authority-payment]
verify_jwt = false

[functions.reminders-generate]
verify_jwt = false

[functions.reminders-digest]
verify_jwt = false